# Generated by Django 5.0.14 on 2025-05-23 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstLocation',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.BigIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_App.mstcompany')),
            ],
            options={
                'db_table': 'Mst_Location',
            },
        ),
    ]
