# Generated by Django 5.0.14 on 2025-05-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0002_mstlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstcompany',
            name='company_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mstlocation',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mstlocation',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mstlocation',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
