# Generated by Django 5.0.14 on 2025-05-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0003_alter_mstcompany_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mst_Category',
            },
        ),
    ]
