# Generated by Django 5.0.14 on 2025-05-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0006_mstrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_code', models.CharField(max_length=20)),
                ('status_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('deactive_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mst_Status',
            },
        ),
    ]
