# Generated by Django 5.0.14 on 2025-05-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0007_mststatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstDepartment',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=250, null=True)),
                ('HOD', models.IntegerField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('location', models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_App.mstlocation')),
            ],
            options={
                'db_table': 'Mst_Department',
            },
        ),
    ]
