# Generated by Django 5.0.14 on 2025-05-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0008_mstdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('user_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_App.mstdepartment')),
                ('location', models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, to='API_App.mstlocation')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='API_App.mstrole')),
            ],
            options={
                'db_table': 'Mst_User',
            },
        ),
    ]
