# Generated by Django 5.0.14 on 2025-05-23 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0009_mstuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstdepartment',
            name='HOD',
            field=models.ForeignKey(db_column='hod', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_App.mstuser'),
        ),
    ]
