# Generated by Django 5.0.14 on 2025-05-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0010_alter_mstdepartment_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstVerifier',
            fields=[
                ('map_dept_veri_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('verifier_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mst_Verifier',
            },
        ),
    ]
