# Generated by Django 5.0.14 on 2025-05-23 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0011_mstverifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstverifier',
            name='location',
            field=models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_App.mstlocation'),
        ),
    ]
