# Generated by Django 5.0.14 on 2025-05-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0012_mstverifier_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstUserRoleConfiguration',
            fields=[
                ('user_role_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=10)),
                ('role_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField()),
                ('created_by', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mst_UserRoleConfiguration',
                'unique_together': {('user_code', 'role_code')},
            },
        ),
    ]
