# Generated by Django 5.0.14 on 2025-05-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0013_mstuserroleconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstcompany',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
