# Generated by Django 5.0.14 on 2025-05-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0014_alter_mstcompany_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstlocation',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
