# Generated by Django 5.0.14 on 2025-05-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0016_alter_mstdepartment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstrole',
            name='deactive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
