# Generated by Django 5.0.14 on 2025-06-02 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0018_mstuser_groups_mstuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnActivity',
            fields=[
                ('ActivityId', models.AutoField(primary_key=True, serialize=False)),
                ('ActivityName', models.CharField(max_length=100)),
                ('TargetDate', models.DateField()),
                ('CreatedOn', models.DateTimeField()),
                ('ModifiedOn', models.DateTimeField(blank=True, null=True)),
                ('Acceptance', models.CharField(blank=True, max_length=5, null=True)),
                ('AdditionalNote', models.TextField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('assign_to', models.ForeignKey(db_column='AssignedUserId', on_delete=django.db.models.deletion.CASCADE, related_name='activities_assigned', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.CASCADE, to='API_App.mstcategory')),
                ('created_by', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.CASCADE, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(db_column='DepartmentId', on_delete=django.db.models.deletion.CASCADE, to='API_App.mstdepartment')),
                ('modified_by', models.ForeignKey(db_column='ModifiedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_modified', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(db_column='StatusId', on_delete=django.db.models.deletion.CASCADE, to='API_App.mststatus')),
                ('user_role', models.ForeignKey(db_column='AssignedUserRoleId', on_delete=django.db.models.deletion.CASCADE, to='API_App.mstrole')),
                ('verifier', models.ForeignKey(db_column='VerifierId', on_delete=django.db.models.deletion.CASCADE, related_name='activities_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Trn_Activity',
            },
        ),
    ]
