# Generated by Django 5.0.14 on 2025-06-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0019_trnactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trnactivity',
            name='user_role',
        ),
        migrations.AddField(
            model_name='trnactivity',
            name='AssignedUserRole',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
