# Generated by Django 5.0.14 on 2025-06-05 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0020_remove_trnactivity_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnActivityTask',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskDescription', models.TextField()),
                ('AssignedOn', models.DateField()),
                ('TargetDate', models.DateField()),
                ('IsPrimary', models.BooleanField(default=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(db_column='ActivityID', on_delete=django.db.models.deletion.CASCADE, to='API_App.trnactivity')),
                ('assigned_to', models.ForeignKey(db_column='AssignedTo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reference_task', models.ForeignKey(blank=True, db_column='ReferenceTaskID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_App.trnactivitytask')),
                ('status', models.ForeignKey(db_column='StatusId', on_delete=django.db.models.deletion.CASCADE, to='API_App.mststatus')),
            ],
            options={
                'db_table': 'Trn_Activity_Task',
            },
        ),
    ]
