# Generated by Django 5.0.14 on 2025-06-11 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0021_trnactivitytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnTaskUpdate',
            fields=[
                ('UpdateId', models.AutoField(primary_key=True, serialize=False)),
                ('ActionOn', models.DateTimeField()),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('action_by', models.ForeignKey(db_column='ActionBy', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('action_status', models.ForeignKey(db_column='ActionStatus', on_delete=django.db.models.deletion.CASCADE, to='API_App.mststatus')),
                ('task_id', models.ForeignKey(db_column='TaskId', on_delete=django.db.models.deletion.CASCADE, to='API_App.trnactivitytask')),
            ],
            options={
                'db_table': 'Trn_Task_Update',
            },
        ),
    ]
