# Generated by Django 5.0.14 on 2025-06-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0022_trntaskupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnactivitytask',
            name='AssignedOn',
            field=models.DateTimeField(),
        ),
    ]
