# Generated by Django 5.0.14 on 2025-06-16 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0023_alter_trnactivitytask_assignedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrnActivityUpdate',
            fields=[
                ('ActUpdateId', models.AutoField(primary_key=True, serialize=False)),
                ('ActionOn', models.DateTimeField()),
                ('Comments', models.TextField(blank=True, null=True)),
                ('action_by', models.ForeignKey(db_column='ActionBy', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('action_status', models.ForeignKey(db_column='ActionStatus', on_delete=django.db.models.deletion.CASCADE, to='API_App.mststatus')),
                ('activity_id', models.ForeignKey(db_column='ActivityId', on_delete=django.db.models.deletion.CASCADE, to='API_App.trnactivity')),
            ],
            options={
                'db_table': 'Trn_Activity_Update',
            },
        ),
    ]
