# Generated by Django 5.0.14 on 2025-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0024_trnactivityupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trnactivity',
            name='ClosedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
