# Generated by Django 5.0.14 on 2025-07-02 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_App', '0025_trnactivity_closedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trnactivity',
            name='assign_to',
            field=models.ForeignKey(db_column='AssignedUserId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
